sudo: required
services:
  - docker
python: '3.6'
before_install:
  - python3 -m pip install pyyaml
script:
  - "./setup.py test"
  - "./setup.py install"
  - pushd test; packagecore 1.2.3 4; popd
before_deploy:
  - packagecore "${TRAVIS_TAG#v}"
deploy:
  provider: releases
  api_key:
    secure: "${SECURE_DEPLOY_KEY}"
  file_glob: true
  file:
    - packagecore-*.deb
    - packagecore-*.pkg.tar.xz
    - packagecore-*.rpm
  skip_cleanup: true
  on:
    tags: true
