site_name: PackageCore
docs_dir: ./doc
pages:
- Home: 'index.md'
- Installing: '01_installing.md'
- Getting Started: '02_intro.md'
- The packagecore Command: '03_command.md'
- The packagecore.yaml File: '04_yaml.md'
- How it Works: '05_howitworks.md'
